---
- name: Configure BCM rack power demo
  hosts: bcm_headnodes
  become: true

  vars:
    rack_power_script_path: /root/collect_rack_power.py
    rack_power_collection: rack_power_collector
    racks:
      - rack_1
      - rack_2
      - rack_3

  tasks:
    - name: Install rack power collection script
      ansible.builtin.copy:
        dest: "{{ rack_power_script_path }}"
        mode: "0755"
        owner: root
        group: root
        content: |
          #!/usr/bin/env python3
          import sys
          import json
          import random

          RACKS = ["rack_1", "rack_2", "rack_3"]

          def initialize():
              metrics = []
              for rack in RACKS:
                  metrics.append({
                      "metric": "totalnodepowerusage",
                      "entity": rack,
                      "unit": "W",
                      "class": "Power/Rack",
                  })
              return metrics

          def sample():
              metrics = []
              for rack in RACKS:
                  if rack == "rack_1":
                      value = random.uniform(100.0, 900.0)
                  elif rack == "rack_2":
                      value = random.uniform(450.0, 460.0)
                  else:
                      value = random.uniform(475.0, 485.0)
                  metrics.append({
                      "metric": "totalnodepowerusage",
                      "entity": rack,
                      "value": value,
                  })
              return metrics

          def main():
              args = sys.argv[1:]
              is_init = any(a == "--initialize" for a in args)
              if is_init:
                  data = initialize()
              else:
                  data = sample()
              print(json.dumps(data))

          if __name__ == "__main__":
              main()

    - name: Configure BCM standalone racks and collection via cmsh
      ansible.builtin.shell: |
        cmsh -c "
        monitoring;
        standalone;
        {% for r in racks %}
        ifnotexists {{ r }} then
          add {{ r }};
          set type Rack;
          commit;
        endif;
        {% endfor %}

        setup;
        ifnotexists {{ rack_power_collection }} then
          add collection {{ rack_power_collection }};
        endif;

        use {{ rack_power_collection }};
        set script {{ rack_power_script_path }};
        set format JSON;
        set interval 30s;

        nodeexecutionfilters;
        active;
        commit;
        exit;

        commit;
        exit;
        "
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ensure dangerous-running-job pod exists
      ansible.builtin.shell: |
        kubectl delete pod dangerous-running-job --ignore-not-found
        kubectl run dangerous-running-job \
          --image=busybox \
          --restart=Never \
          --command -- sh -c "echo Dangerous job is running for 1 day; sleep 86400"
      args:
        executable: /bin/bash
